name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Windows Config
        if: runner.os == 'Windows'
        run: |
          git config --system core.longpaths true
          echo "Enabled long paths in git"

          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          echo "Enabled long paths in registry"

          $git_link = "C:\Program Files\Git\usr\bin\link.exe"
          if (Test-Path $git_link) {
              Rename-Item $git_link "_link.exe"
          }
          echo "Removed link.exe in git"

      - name: Checkout self
        uses: actions/checkout@v6

      # - name: Setup MSVC
      #   if: runner.os == 'Windows'
      #   uses: ilammy/msvc-dev-cmd@v1
      #   with:
      #     toolset: 14.29
      #     arch: x64

      # - name: Setup Spectre
      #   if: runner.os == 'Windows'
      #   shell: pwsh
      #   run: |
      #     7z x spectre.7z -o"$env:VCToolsInstallDir\lib"
      #     $env:LIBPATH = "$env:VCToolsInstallDir\lib\spectre\x64;" + $env:LIBPATH

      - name: Checkout target
        uses: actions/checkout@v6
        with:
          repository: zed-industries/zed
          ref: refs/tags/v1.20.2
          path: zed

      - name: Copy config file
        run: |
          cp .cargo/config.toml zed/.cargo/

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y pkg-config libfontconfig1-dev libglib2.0-dev libx11-dev libasound2-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev

      - name: Create release dir
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            mkdir -p release/linux/zed/bin release/linux/zed/libexec
          fi

          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            mkdir -p release/windows/zed/bin
          fi

      - name: Build cli
        shell: bash
        run: |
          cd zed/crates/cli
          cargo b -r
          cd -

          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            mv zed/target/release/cli release/linux/zed/bin/zed
          fi

          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            mv zed/target/release/cli.exe release/windows/zed/bin/zed.exe
          fi

      - name: Build editor
        shell: bash
        run: |
          cd zed
          cargo b -r
          cd -

          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            mv zed/target/release/zed release/linux/zed/libexec
          fi

          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            mv zed/target/release/zed.exe release/windows/zed
          fi

      - name: Linux archive
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v6
        with:
          name: zed_${{ runner.os }}
          path: |
            release/linux/zed

      - name: Windows archive
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v6
        with:
          name: zed_${{ runner.os }}
          path: |
            release/windows/zed
